# Generated by Django 4.1.7 on 2025-06-23 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('money_manage', '0002_customuser_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.group'),
        ),
        migrations.AlterField(
            model_name='utilitybillreminder',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.group'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
