# Generated by Django 4.1.7 on 2025-07-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('FRIENDS', 'Friends'), ('FAMILY', 'Family'), ('BUSINESS', 'Business'), ('ROOMMATES', 'Roommates'), ('TRIP', 'Trip'), ('PARTY', 'Party'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
